import { render, screen } from "@testing-library/react";
import IntroductionPost from '../app/blog/IntroductionPost';
import '@testing-library/jest-dom';

const post = {
    id:1,
    bodyId:1,
    autogenerated:false,
    topic:"Introduction",
    title:"Introduction",
    questionPosedToOpenAi:"Into all manual",
    createdOn:"2023-12-23T00:00:00Z",
    createdBy:"init",
    active:true,
    category:"Introduction",
    imageUrl:"https://source.unsplash.com/random?wallpapers",
    imageText:"Thank you unsplash!",
    body:"Hello! Is it me you're looking for?"
}

//test block
test("IntroductionPost renders correctly", () => {

    // render the component on virtual dom
    render(<IntroductionPost post={post} />);
    //select the elements you want to interact with
    const title = screen.getByTestId("title");
    const body = screen.queryByTestId("body");
    //assert the expected result
    expect(title).toBeInTheDocument;
    expect(body).toBeInTheDocument;
    expect(screen.getByText(post.title)).toBeInTheDocument();
    expect(screen.getByText(post.body)).toBeInTheDocument();
})
