import { render, screen } from "@testing-library/react";
import Main from '../app/blog/Main';
import '@testing-library/jest-dom';

const postProps = [{
    id:1,
    bodyId:1,
    autogenerated:false,
    topic:"Introduction",
    title:"Introduction",
    questionPosedToOpenAi:"Into all manual",
    createdOn: Date.now(),
    createdBy:"init",
    active:true,
    category:"Introduction",
    imageUrl:"https://source.unsplash.com/random?wallpapers",
    imageText:"Thank you unsplash!",
    body:"Hello! Is it me you're looking for?"
}]

//test block
test("Main renders correctly", () => {
    const testTitle = "My test"
    // render the component on virtual dom
    render(<Main posts={postProps} title={testTitle}/>);
    //select the elements you want to interact with
    const title = screen.getByTestId("title");
    const posts = screen.queryByTestId("posts");
    //assert the expected result
    expect(title).toBeInTheDocument;
    expect(posts).toBeInTheDocument;
    expect(screen.getByText(testTitle)).toBeInTheDocument();
})
