import { render, screen } from "@testing-library/react";
import Post from '../app/blog/Post';
import '@testing-library/jest-dom';

const { format } = require("date-fns");
const mockDateObject = new Date("2023-02-26T22:42:16.652Z")
const postProps = {
    id:1,
    bodyId:1,
    autogenerated:false,
    topic:"Introduction",
    title:"Introduction",
    questionPosedToOpenAi:"Into all manual",
    createdOn: mockDateObject,
    createdBy:"init",
    active:true,
    category:"Introduction",
    imageUrl:"https://source.unsplash.com/random?wallpapers",
    imageText:"Thank you unsplash!",
    body:"Hello! Is it me you're looking for?"
}

//test block
test("Post renders correctly", () => {
    // render the component on virtual dom
    render(<Post post={postProps} key={postProps.id}/>);
    //select the elements you want to interact with
    const title = screen.getByTestId("post-title");
    const caption = screen.queryByTestId("caption");
    const question = screen.queryByTestId("queston");
    const answer = screen.queryByTestId("answer");

    //assert the expected result
    expect(title).toBeInTheDocument;
    expect(caption).toBeInTheDocument;
    expect(question).toBeInTheDocument;
    expect(answer).toBeInTheDocument;
    expect(screen.getByText(postProps.title)).toBeInTheDocument();
    expect(screen.getByText(postProps.questionPosedToOpenAi)).toBeInTheDocument();
})
