version: '3.8'
services:
  db:
    build: .
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
    driver: local