package model

import (
	"time"
)

// Blog ..
type Blog struct {
	Id            int
	BodyId        int
	Autogenerated bool
	Topic         string
	Generated     string
	Written       string
	CreatedOn     time.Time
	CreatedBy     string
	Active        bool
	CategoryId    int
}

// BlogRepository ..
type BlogRepository interface {
	GetAll() (*Blog, error)
	Save(Blog *Blog) error
}
