package model

import (
	"time"
)

// Blog ..
type Blog struct {
	Id                    int
	BodyId                int
	Autogenerated         bool
	Topic                 string
	Title                 string
	QuestionPosedToOpenAi string
	CreatedOn             time.Time
	CreatedBy             string
	Active                bool
	Category              string
}

// BlogRepository ..
type BlogRepository interface {
	GetAll() ([]*Blog, error)
	Save(Blog *Blog) error
	Close()
}
