package model

import (
	"time"
)

// Blog ..
type Blog struct {
	Id                    int       `json:"id"`
	BodyId                int       `json:"bodyId"`
	Autogenerated         bool      `json:"autogenerated"`
	Topic                 string    `json:"topic"`
	Title                 string    `json:"title"`
	QuestionPosedToOpenAi string    `json:"questionPosedToOpenAi"`
	CreatedOn             time.Time `json:"createdOn"`
	CreatedBy             string    `json:"createdBy"`
	Active                bool      `json:"active"`
	Category              string    `json:"category"`
	ImageUrl              string    `json:"imageUrl"`
	ImageText             string    `json:"imageText"`
	Body                  string    `json:"body"`
}

// BlogRepository ..
type BlogRepository interface {
	GetAll() ([]*Blog, error)
	Categories() ([]string, error)
	Save(Blog *Blog) error
	Close()
}
