export type BlogPost = {
    id: number,
	bodyId: number,   
	autogenerated: boolean,
	topic: string,
	title: string,
	questionPosedToOpenAi: string,
	createdOn: Date,
	createdBy: string,
	active: boolean,
	category: string
}

export type Section = {
    title: string,
    url: string
}